#!/bin/bash
# Maintain local tracking braches

# Author:  Valentin Haenel <valentin.haenel@gmx.de>
# Licence: wtfpl <http://sam.zoy.org/wtfpl/>

# use shUnit

if [ $# -eq 0 ]; then
    set -- -h
fi

OPTS_SPEC="\
git tracking start [--force|-f] <remote>/<branch>
git tracking stop
git tracking fast-forward
git tracking status
git tracking review
--
h,help        show the help
 options for 'start'
f,force       implies stop tracking first
"

eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"

echo "Options: $*"

. $(git --exec-path)/git-sh-setup

while [ $# -gt 0 ]; do
    opt="$1"
    shift
    case "$opt" in
        -f) force=1 ;;
        --) break ;;
    esac
done

command="$1"
shift

croak() {
    echo -e "error: $@"
    exit 1
}

finish() {
    echo -e "Done: $@"
    exit 1
}

BRANCH=$( git branch | grep ^* | sed 's/^\* //' )
if [[ $BRANCH == '(no branch)' ]] ; then
    croak 'You have a detached HEAD, this can not track anything.'
fi
REMOTE=$( git config branch.$BRANCH.remote )
REMOTE_BRANCH=$( git config branch.$BRANCH.merge | sed 's,^refs/heads/,,')

check_no_tracking (){
if [[ -z $REMOTE ]] ; then
    croak "Your branch '$BRANCH' isn't tracking anything."
fi
}

do_stop_tracking() {
    check_no_tracking
    git config --remove-section branch.$BRANCH
    echo "Branch '$BRANCH' is no longer tracking '$REMOTE/$REMOTE_BRANCH'."
}

fast_forward_tracking() {
    check_no_tracking
    if [[ -n $REMOTE && -n $( git config branch.$BRANCH.merge) ]] ; then
        remote_ahead_local=$( git log --oneline $BRANCH..$REMOTE/$BRANCH)
        local_ahead_remote=$( git log --oneline $REMOTE/$BRANCH..$BRANCH)
        if [[ -z $remote_ahead_local && -z $local_ahead_remote ]] ; then
                if [[ $( git rev-parse $BRANCH )  == $( git rev-parse $REMOTE/$BRANCH ) ]] ; then
                    croak "Your branch '$BRANCH' points to same commit as '$REMOTE/$BRANCH', doing nothing."
                else
                    echo "Dude..."
                    exit 42
                fi
        fi
        if [[ -z $remote_ahead_local && -n $local_ahead_remote ]] ; then
            croak "Your branch '$BRANCH'is ahead of '$REMOTE/$BRANCH', perhaps you want to push?"
        fi
        if [[ -n $local_ahead_remote && -n $remote_ahead_local ]] ; then
            croak "Your branches '$BRANCH' and '$REMOTE/$BRANCH' and have diverged, fast-forward not possible!"
        fi
        if [[ -n $remote_ahead_local && -z $local_ahead_remote ]] ; then
            echo "Fast-forward '$BRANCH' to '$REMOTE/$BRANCH'."
            git merge --ff-only $REMOTE/$BRANCH
            exit 0
        fi
    fi
}

start_tracking(){
    if [[ -n $REMOTE && -z $force ]] ; then
        croak "Your branch '$BRANCH' is already tracking '$REMOTE/$BRANCH'\n"\
              "Either use 'git tracking stop' first or use --force(-f)."
    elif [[ -n $REMOTE && $force ]] ; then
        do_stop_tracking
    fi
    if [[ $1 != */* ]]; then
        croak "Remote tracking branch was not specified as <remote>/<branch>.\n"\
              "Available remote branches are:\n"\
              $( git branch -r )
    fi
    remote_branch=$( echo $1 | sed 's_^[^/]*/__')
    new_remote=$( echo $1 | sed 's,/.*$,,')
    if [[ -z $( git remote | grep  -x $new_remote) ]]  ;then
        croak "Can not start tracking, remote '$new_remote' does not exist!"
    fi
    if [[ -z $( git branch -r | grep -x $new_remote/$remote_branch ) ]] ; then
        croak "Can not start tracking, remote '$new_remote' does not appear to have a branch '$remote_branch'"
    fi
    git config branch.$BRANCH.remote $new_remote
    git config branch.$BRANCH.merge 'refs/heads/'$remote_branch
    echo "Branch '$BRANCH' setup to track remote branch '$remote_branch' from '$new_remote'."
    exit 0
}

stop_tracking() {
    do_stop_tracking
    exit 0
}

review_tracking() {
    check_no_tracking
    # TODO check that the remote tracking branch is actually ahead
    git log $@ $BRANCH..$REMOTE/$BRANCH
}

status_tracking(){
    #rewrite this and format output neater
    git branch -vv
    exit 0
}

case "$command" in
    stop|fast-forward|status|review)
        [[ $force -gt 0 ]] && croak "[-f|--force] can only be used with 'start'";;
    start) ;;
    *) croak "Unknown command '$command'" ;;
esac

$command"_tracking" "$@"
